name: myenv
channels:
  - https://conda.anaconda.org/pytorch
  - https://conda.anaconda.org/conda-forge
  - https://anacondastaging.ices.on.ca/api/repo/main
  - https://repo.anaconda.com/pkgs/main
  - https://anacondastaging.ices.on.ca/api/repo/conda-forge
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - _py-xgboost-mutex=2.0=cpu_0
  - _r-mutex=1.0.0=anacondar_1
  - argcomplete=1.12.3=pyhd8ed1ab_2
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bayesian-optimization=1.1.0=py_0
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_33
  - blas=1.0=mkl
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - cairo=1.14.12=h8948797_3
  - certifi=2021.10.8=py37h89c1867_1
  - cudatoolkit=10.2.89=h8f6ccaa_8
  - curl=7.64.0=h646f8bb_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py37hcd2ae1e_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - eli5=0.11.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h2531618_2
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.10.4=h5ab3b9f_0
  - fribidi=1.0.10=h7b6447c_0
  - gcc_impl_linux-64=7.5.0=hda68d29_13
  - gcc_linux-64=7.5.0=h47867f9_33
  - gfortran_impl_linux-64=7.5.0=h56cb351_19
  - gfortran_linux-64=7.5.0=h78c8a43_33
  - glib=2.63.1=h5a9c865_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h23475e2_0
  - graphviz=2.40.1=h21bd128_2
  - gsl=2.4=h14c3975_4
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gxx_impl_linux-64=7.5.0=h64c220c_13
  - gxx_linux-64=7.5.0=h555fc39_33
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=he6710b0_3
  - imbalanced-learn=0.8.1=pyhd8ed1ab_0
  - importlib-metadata=4.8.1=py37h89c1867_1
  - importlib_metadata=4.8.1=hd8ed1ab_1
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.8.0=py37h6531663_0
  - ipython=7.29.0=py37h6531663_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py37h89c1867_3
  - jinja2=3.0.0=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py37h89c1867_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - kiwisolver=1.3.1=py37h2531618_0
  - krb5=1.16.3=hc83ff2d_1000
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libcurl=7.64.0=h01ee5af_0
  - libedit=3.1.20210714=h7f8727e_0
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=11.2.0=h1d223b6_10
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1d223b6_10
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.8.0=h1ad7b7a_1003
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxgboost=1.3.3=h2531618_0
  - libxml2=2.9.12=h03d6c58_0
  - lz4-c=1.9.3=h295c915_1
  - make=4.3=hd18ef5c_1
  - markupsafe=2.0.1=py37h27cfd23_0
  - matplotlib=3.2.2=0
  - matplotlib-base=3.2.2=py37hef1b27d_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.0=py37h42c9631_2
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.20.3=py37hf144106_0
  - numpy-base=1.20.3=py37h74d4b33_0
  - olefile=0.46=py37_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.0.2u=h516909a_0
  - pandas=1.2.3=py37ha9443f7_0
  - pango=1.42.4=h049681c_0
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.2=pyhd8ed1ab_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py37h2c7a002_0
  - pip=21.2.2=py37h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - prompt-toolkit=3.0.22=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - py-xgboost=1.3.3=py37h06a4308_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h05f1152_2
  - python=3.7.0=hd21baee_1006
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-graphviz=0.16=pyhd3eb1b0_1
  - python_abi=3.7=2_cp37m
  - pytorch=1.8.1=py3.7_cuda10.2_cudnn7.6.5_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=22.1.0=py37h336d617_0
  - qt=5.9.6=h8703b6f_2
  - r-assertthat=0.2.0=r351h6115d3f_0
  - r-base=3.5.1=h1e0a451_2
  - r-cli=1.0.0=r351h6115d3f_1
  - r-colorspace=1.3_2=r351h96ca727_0
  - r-crayon=1.3.4=r351h6115d3f_0
  - r-dichromat=2.0_0=r351h6115d3f_4
  - r-digest=0.6.15=r351h96ca727_0
  - r-fansi=0.2.3=r351h96ca727_0
  - r-ggplot2=3.0.0=r351h6115d3f_0
  - r-glue=1.3.0=r351h96ca727_0
  - r-gtable=0.2.0=r351h6115d3f_0
  - r-labeling=0.3=r351h6115d3f_4
  - r-lattice=0.20_35=r351h96ca727_0
  - r-lazyeval=0.2.1=r351h96ca727_0
  - r-magrittr=1.5=r351h6115d3f_4
  - r-mass=7.3_50=r351h96ca727_0
  - r-matrix=1.2_14=r351h96ca727_0
  - r-mgcv=1.8_24=r351h96ca727_0
  - r-munsell=0.5.0=r351h6115d3f_0
  - r-nlme=3.1_137=r351ha65eedd_0
  - r-pillar=1.3.0=r351h6115d3f_0
  - r-plyr=1.8.4=r351h29659fb_0
  - r-proc=1.12.1=r351h29659fb_0
  - r-r6=2.2.2=r351h6115d3f_0
  - r-rcolorbrewer=1.1_2=r351h6115d3f_0
  - r-rcpp=0.12.18=r351h29659fb_0
  - r-reshape2=1.4.3=r351h29659fb_0
  - r-rlang=0.2.1=r351h96ca727_0
  - r-scales=0.5.0=r351h29659fb_0
  - r-stringi=1.2.4=r351h29659fb_0
  - r-stringr=1.3.1=r351h6115d3f_0
  - r-tibble=1.4.2=r351h96ca727_0
  - r-utf8=1.1.4=r351h96ca727_0
  - r-viridislite=0.3.0=r351h6115d3f_0
  - r-withr=2.1.2=r351h6115d3f_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.24.1=py37ha9443f7_0
  - scipy=1.7.1=py37h292c36d_2
  - seaborn=0.11.2=hd8ed1ab_0
  - seaborn-base=0.11.2=pyhd8ed1ab_0
  - setuptools=58.0.4=py37h06a4308_0
  - singledispatch=3.7.0=pyhd3eb1b0_1001
  - sip=4.19.8=py37hf484d3e_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.33.0=h62c20be_0
  - statsmodels=0.13.1=py37hb1e94ed_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tabulate=0.8.9=py37h06a4308_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h1ccaba5_0
  - tktable=2.10=hb7b940f_3
  - torchvision=0.9.1=py37_cu102
  - tornado=6.1=py37h27cfd23_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - x264=1!157.20191217=h7b6447c_0
  - xgboost=1.3.3=py37h06a4308_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
prefix: /XXXXXX/.conda/envs/myenv
